### ISSUE TITLE
Is the password in config real?

### ISSUE THREAD

**Issue by jewzaam** [aprajshekhar/splunk-image-stats#1]
https://github.com/aprajshekhar/splunk-image-stats/blob/master/config.yml#L3

If so, I recommend:
1. remove it from git (put in junk, require local checkout to set it correctly)
2. change password for this user

If it's not real, thanks!

**Comment by aprajshekhar** [comment]
Thanks for opening this issue. And sorry for late reply.  I have  removed them. Will add comments to the config to detail what each value does..
